import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Nav from "../components/Nav";
import Footer from "../components/Footer";


const manrope = Manrope({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body  className='flex min-h-dvh flex-col' >
        <Nav />
        <div className="grow">
        {children}
        </div>
        <Footer />
      </body>

    </html>
  );
}
